Repository RLOpenCatalyst/service-workbench-on-aws, pull requests merged in 2021-06, with the labels that each got.

#16 Feat rstudio albpermission
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
Labels: size/s

#17 Feat alb lockservice
  addons/addon-base-raas/packages/base-raas-services/lib/alb/__tests__/alb-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/alb/alb-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/check-launch-dependency/check-launch-dependency.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/launch-product/launch-product.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/terminate-launch-dependency/terminate-launch-dependency.js
Labels: size/m

#19 Feat rstudio metadata - Add Meta-Data to Partner provided Workspace Types
  addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/env-type-candidate-service.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/models/environment-types/EnvTypeCandidate.js
  addons/addon-environment-sc-ui/packages/environment-type-mgmt-ui/src/parts/environment-types/EnvTypeCandidatesList.js
  main/solution/ui/src/css/index.css
Labels: size/s

#24 Feat rstudio editcidrs
  addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/environments-sc/parts/ScEnvironmentUpdateCidrs.js
  addons/addon-base-raas/packages/base-raas-services/lib/alb/__tests__/alb-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/alb/alb-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-cidr-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-cidr-service.js
  addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
Labels: size/m

#27 Feat rstudio albpermission
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
Labels: size/xs

#36 Update Develop branch with feat-alb-lockservice
  addons/addon-base-raas/packages/base-raas-services/lib/alb/__tests__/alb-service.test.js
  addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/check-launch-dependency.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/terminate-launch-dependency.test.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/check-launch-dependency/check-launch-dependency.js
  addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/terminate-launch-dependency/terminate-launch-dependency.js
Labels: size/m

#37 Updating Develop branch with the feat-rstudio-albpermission
  addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
Labels: size/xs
